import "./globals.css";
// import { Poppins } from "next/font/google";

{
  /* Font Styling */
}
// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'],
//   style: ['normal', 'italic'],
//   display: 'swap',
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/style.css" />
      </head>
      <body>
        {/* <body className={poppins.className}> */} {/* Font Styling */}
        {children}
      </body>
    </html>
  );
}
